# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 02:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('addr', '0002_auto_20180626_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='approved_friend',
            new_name='approved_address',
        ),
        migrations.AlterField(
            model_name='address',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 26, 2, 15, 26, 832635, tzinfo=utc)),
        ),
    ]
