# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 05:05
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('addr', '0004_auto_20180626_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('phon_number_1', models.CharField(max_length=20)),
                ('phon_number_2', models.CharField(blank=True, max_length=20, null=True)),
                ('e_mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2018, 6, 26, 5, 5, 48, 734669, tzinfo=utc))),
                ('approved_friend', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.RemoveField(
            model_name='address',
            name='author',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
