# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 05:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('addr', '0005_auto_20180626_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('approved_memo', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='friend',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 26, 5, 49, 28, 85971, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='memo',
            name='Friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memo', to='addr.Friend'),
        ),
    ]
